title: Folders
email: support@jbmorley.co.uk
description: Offline library management for your files
baseurl: ""
url: "https://folders.jbmorley.co.uk"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-environment-variables
destination: ../_site

defaults:
  - values:
      layout: "default"
