name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:

  macos-build:

    runs-on: inseven-macos-14

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build and test
      env:
        APPLE_DEVELOPMENT_CERTIFICATE_BASE64: ${{ secrets.PERSONAL_APPLE_DEVELOPMENT_CERTIFICATE_BASE64 }}
        APPLE_DEVELOPMENT_CERTIFICATE_PASSWORD: ${{ secrets.PERSONAL_APPLE_DEVELOPMENT_CERTIFICATE_PASSWORD }}
        APPLE_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.PERSONAL_APPLE_DISTRIBUTION_CERTIFICATE_BASE64 }}
        APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.PERSONAL_APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
        MACOS_DEVELOPER_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.PERSONAL_MACOS_DEVELOPER_INSTALLER_CERTIFICATE_BASE64 }}
        MACOS_DEVELOPER_INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.PERSONAL_MACOS_DEVELOPER_INSTALLER_CERTIFICATE_PASSWORD }}

        APPLE_API_KEY_BASE64: ${{ secrets.PERSONAL_APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ISSUER_ID: ${{ secrets.PERSONAL_APPLE_API_KEY_ISSUER_ID }}
        APPLE_API_KEY_ID: ${{ secrets.PERSONAL_APPLE_API_KEY_ID }}

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE: ${{ github.ref == 'refs/heads/main' }}

      run: |
        scripts/build.sh

    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        path: build/build-*.zip
        if-no-files-found: error

    - name: Archive build direcctory
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-directory
        path: build

  linux-build:
    env:
      CARGO_TERM_COLOR: always

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
    - uses: actions/checkout@v4
      run: |
        sudo apt-get install -y \
          libglib2.0-dev \
          libgdk-pixbuf2.0-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libgraphene-1.0-dev \
          libgtk-4-dev \
          libadwaita-1-dev

    - name: Build and test
      run: |
        cd gtk
        cargo build --verbose
        cargo test --verbose
